module DBotQuery
  module Commands
    class CommandBase
      type output = Hash[String, untyped] | Array[String] | Hash[Symbol, untyped]

      @result: output

      attr_reader result: output

      def initialize: () -> void

      def execute!: (String file) -> void

      def perform: (Models::DataFile) -> untyped
    end
  end
end

