module DBotQuery
  module Commands
    class PackageSearchCommand < CommandBase
      attr_reader package: String

      def initialize: (package: String) -> void

      def perform: (CommandBase::input) -> Array[String]

      private

      def where_package: (CommandBase::input) -> CommandBase::input
    end
  end
end
