module DBotQuery
  module Commands
    class PackageSearchCommand < CommandBase
      attr_reader package: String

      def initialize: (package: String) -> void

      def perform: (Models::DataFile) -> Array[String]
    end
  end
end
