module DBotQuery
  module Commands
    class SummaryCommand < CommandBase
      attr_reader severity: Models::SecurityAdvisory::severity?
      attr_reader state: Models::Alert::state?

      @severity: Models::SecurityAdvisory::severity?
      @state: Models::Alert::state?

      def initialize: (state: Models::Alert::state?, severity: Models::SecurityAdvisory::severity?) -> void

      def perform: (Models::DataFile) -> { count: Integer }
    end
  end
end
