module DBotQuery
  module Commands
    class SummaryCommand < CommandBase
      attr_reader severity: CommandBase::severity?
      attr_reader state: CommandBase::state?

      @severity: CommandBase::severity?
      @state: CommandBase::state?

      def initialize: (state: CommandBase::state?, severity: CommandBase::severity?) -> void

      private

      def state_filter: (CommandBase::input) -> CommandBase::input
      def severity_filter: (CommandBase::input) -> CommandBase::input
    end
  end
end
