module DBotQuery
  class CLI < Thor
    # These are fixups for Thor missing annotations
    def self.long_desc: (String) -> void

    @command: Commands::CommandBase

    def package_search: -> void

    def repo_sla_stats: -> void

    def sla_stats: -> void

    def summary: -> void

    private

    def color_enabled?: -> bool

    def run!: (Commands::CommandBase) -> void
  end
end
