module DBotQuery
  VERSION: String

  SLA_DEFINITION: Hash[Models::SecurityAdvisory::severity, Integer]

  SCHEMA_PATH: String

  SCHEMA: Hash[untyped, untyped]

  class Error < StandardError
  end

  def self.schema: () -> Hash[untyped, untyped]
end
