module DBotQuery
  VERSION: String

  SLA_DEFINITION: Hash[Commands::CommandBase::severity, Integer]

  SCHEMA_PATH: String

  class Error < StandardError
  end

  def self.schema: () -> Hash[untyped, untyped]
end
